-- MySQL Script generated by MySQL Workbench
-- Tue Feb 27 21:21:08 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema real_estate
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema real_estate
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `real_estate` DEFAULT CHARACTER SET utf8 ;
USE `real_estate` ;

-- -----------------------------------------------------
-- Table `real_estate`.`type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `real_estate`.`type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `label` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `real_estate`.`city`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `real_estate`.`city` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `label` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `real_estate`.`proprety`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `real_estate`.`proprety` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type_id` INT NOT NULL,
  `front_photo` VARCHAR(254) NULL,
  `price` VARCHAR(45) NULL,
  `bedrooms` INT(45) NULL,
  `bathrooms` INT(45) NULL,
  `pets_allowed` TINYINT NULL,
  `adress` VARCHAR(45) NULL,
  `for_rent` TINYINT NULL,
  `square_metters` INT(45) NULL,
  `create_time` TIMESTAMP NULL,
  `city_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_proprety_type1_idx` (`type_id` ASC),
  INDEX `fk_proprety_city1_idx` (`city_id` ASC),
  CONSTRAINT `fk_proprety_type1`
    FOREIGN KEY (`type_id`)
    REFERENCES `real_estate`.`type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_proprety_city1`
    FOREIGN KEY (`city_id`)
    REFERENCES `real_estate`.`city` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `real_estate`.`Amenity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `real_estate`.`Amenity` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `label` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `real_estate`.`proprety_has_Amenity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `real_estate`.`proprety_has_Amenity` (
  `proprety_id` INT NOT NULL,
  `Amenity_id` INT NOT NULL,
  PRIMARY KEY (`proprety_id`, `Amenity_id`),
  INDEX `fk_proprety_has_Amenity_Amenity1_idx` (`Amenity_id` ASC),
  INDEX `fk_proprety_has_Amenity_proprety1_idx` (`proprety_id` ASC),
  CONSTRAINT `fk_proprety_has_Amenity_proprety1`
    FOREIGN KEY (`proprety_id`)
    REFERENCES `real_estate`.`proprety` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_proprety_has_Amenity_Amenity1`
    FOREIGN KEY (`Amenity_id`)
    REFERENCES `real_estate`.`Amenity` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `real_estate`.`timestamps`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `real_estate`.`timestamps` (
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL);


-- -----------------------------------------------------
-- Table `real_estate`.`photos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `real_estate`.`photos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `photo_path` VARCHAR(254) NULL,
  `proprety_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_photos_proprety1_idx` (`proprety_id` ASC),
  CONSTRAINT `fk_photos_proprety1`
    FOREIGN KEY (`proprety_id`)
    REFERENCES `real_estate`.`proprety` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
